### ISSUE TITLE
Only 1 block is dropped

### ISSUE THREAD

**Issue by DeerAndy** [Aurilisdev/Timber#1]
I'm using PaperMC which is a Spigot fork, and when I chop the bottom block for trees it only provides that block and makes all others disappear.. I'm sure this isn't intended and would like some help getting it to work as it should.

**Comment by aurilisdev** [comment]
What do you mean by that it only "provides" that block?

**Comment by DeerAndy** [comment]
> 
> 
> What do you mean by that it only "provides" that block?

The block you break to get the whole tree to "fall" is the only piece of the tree that drops. So if a tree has 4 blocks of oak you only get 1/4 oak logs.

**Comment by aurilisdev** [comment]
This is an issue with papermc
